#pragma once

#define IDI_APPICON                 1

#define IDR_FONT_BENTONSANS_REGULAR 101
#define IDR_FONT_HELVETICA_BOLD     102
#define IDR_FONT_HELVETICA_REGULAR  103

#define IDR_IMG_VEHICLE_COYWOLF     201
#define IDR_IMG_VEHICLE_MIRAGE      202
#define IDR_IMG_VEHICLE_PIONEER     203
#define IDR_IMG_VEHICLE_VEGAS       204

#define IDR_IMG_WEAPON_FRAG         301
#define IDR_IMG_WEAPON_OSMAW        302
#define IDR_IMG_WEAPON_STABBANL9    303
#define IDR_IMG_WEAPON_UL3          304

#define IDR_IMG_PLAYER_ROLE_GUNSLINGER   401
#define IDR_IMG_PLAYER_ROLE_RIFLEMAN     402
#define IDR_IMG_PLAYER_ROLE_GRAFFITI     403
#define IDR_IMG_PLAYER_ROLE_EPIDEMIC2024 404
#define IDR_IMG_PLAYER_ROLE_GRAFFITI_SHORT 405

#define IDR_IMG_CONTACT_UNLOCKS_ARLON    501
#define IDR_IMG_CONTACT_UNLOCKS_BIRTH    502
#define IDR_IMG_CONTACT_UNLOCKS_LUCAS    503
#define IDR_IMG_CONTACT_UNLOCKS_BRITNEY  504

#define IDR_IMG_CONTACT_MISSIONS_BIRTH   505
#define IDR_IMG_CONTACT_MISSIONS_TIPTOE  506
#define IDR_IMG_CONTACT_MISSIONS_MIGUEL  507
#define IDR_IMG_CONTACT_MISSIONS_CHIZA   508
